{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cnskunkworks-prometheus-exporter.serviceAccountName" . }}
  labels:
    {{- include "cnskunkworks-prometheus-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cnskunkworks-prometheus-exporter.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cnskunkworks-prometheus-exporter.serviceAccountName" . }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ include "cnskunkworks-prometheus-exporter.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cnskunkworks-prometheus-exporter.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
  